use anyhow::Result;
use std::{fmt::Write, fs};

pub fn render_html(chronicle_path: &str, output_path: &str) -> Result<()> {
    let raw = fs::read_to_string(chronicle_path)?;

    // Use a String + write! instead of format!-per-line collect (avoids allocation per entry)
    let mut entries = String::with_capacity(raw.len() * 2);
    for line in raw.lines().filter(|l| !l.trim().is_empty()) {
        write!(entries, "<p class=\"entry\">{}</p>\n", html_escape(line))?;
    }

    let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M");

    let html = format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>The Ironveil Chronicle</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=IM+Fell+English:ital@0;1&display=swap');
  body {{
    background: #1a1510; color: #c8be9e;
    font-family: 'IM Fell English', Georgia, serif;
    max-width: 780px; margin: 0 auto; padding: 3rem 2rem; line-height: 1.8;
  }}
  h1 {{ text-align: center; color: #b48c3c; font-size: 2.4rem;
        letter-spacing: 0.1em; border-bottom: 1px solid #4a3f2a;
        padding-bottom: 1rem; margin-bottom: 2rem; }}
  .entry {{ margin: 0.4rem 0; font-size: 1.05rem;
            border-left: 2px solid #3a3020; padding-left: 1rem; }}
  .entry:hover {{ border-left-color: #b48c3c; background: rgba(180,140,60,0.04); }}
  footer {{ text-align: center; margin-top: 3rem; color: #5a5040;
            font-style: italic; font-size: 0.9rem;
            border-top: 1px solid #3a3020; padding-top: 1rem; }}
</style>
</head>
<body>
<h1>The Ironveil Chronicle</h1>
{entries}
<footer>Generated by IRONVEIL &mdash; {timestamp}</footer>
</body>
</html>"#);

    fs::write(output_path, html)?;
    println!("Chronicle rendered to: {output_path}");
    Ok(())
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
     .replace('<', "&lt;")
     .replace('>', "&gt;")
     .replace('"', "&quot;")
}
